//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Mariana Artavia Vene/Documents/I SEMESTRE 2023/Compiladores e Interpretes/ConsoleCompi/ConsoleCompi/src\MiniCSharpParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public partial class MiniCSharpParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LIST=1, INT_ID=2, STRING_ID=3, CHAR_ID=4, BOOL_ID=5, DOUBLE_ID=6, CLASS=7, 
		USING=8, VOID=9, IF=10, ELSE=11, WHILE=12, FOR=13, BREAK=14, RETURN=15, 
		READ=16, WRITE=17, NEW=18, DELMETHOD=19, ADDMETHOD=20, LENMETHOD=21, DEL=22, 
		ADD=23, LEN=24, BOOL=25, INT=26, DOUBLE=27, STRINGCONST=28, CHARCONST=29, 
		EscapeSequence=30, ASSIGN=31, AND=32, OR=33, PLUS=34, MINUS=35, PLUSPLUS=36, 
		MINUSMINUS=37, MULT=38, DIV=39, MOD=40, EQUALS=41, NOTEQUALS=42, LESSTHAN=43, 
		GREATERTHAN=44, LESSOREQUALS=45, GREATOREQUALS=46, DOT=47, SEMICOLON=48, 
		COMMA=49, LEFTPAREN=50, RIGHTPAREN=51, LEFTBRACK=52, RIGHTBRACK=53, LEFTSBRACK=54, 
		RIGHTSBRACK=55, IDENTIFIER=56, COMMENT=57, BLOCKCOMMENT=58, WS=59;
	public const int
		RULE_program = 0, RULE_using = 1, RULE_varDecl = 2, RULE_classDecl = 3, 
		RULE_methodDecl = 4, RULE_formPars = 5, RULE_type = 6, RULE_statement = 7, 
		RULE_block = 8, RULE_actPars = 9, RULE_condition = 10, RULE_condTerm = 11, 
		RULE_condFact = 12, RULE_cast = 13, RULE_expr = 14, RULE_term = 15, RULE_factor = 16, 
		RULE_designator = 17, RULE_relop = 18, RULE_addop = 19, RULE_mulop = 20, 
		RULE_ident = 21;
	public static readonly string[] ruleNames = {
		"program", "using", "varDecl", "classDecl", "methodDecl", "formPars", 
		"type", "statement", "block", "actPars", "condition", "condTerm", "condFact", 
		"cast", "expr", "term", "factor", "designator", "relop", "addop", "mulop", 
		"ident"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "'int'", "'string'", "'char'", "'bool'", "'double'", "'class'", 
		"'using'", "'void'", "'if'", "'else'", "'while'", "'for'", "'break'", 
		"'return'", "'read'", "'write'", "'new'", "'.del'", "'.add'", "'.len'", 
		"'del'", "'add'", "'len'", null, null, null, null, null, null, "'='", 
		"'&&'", "'||'", "'+'", "'-'", "'++'", "'--'", "'*'", "'/'", "'%'", "'=='", 
		"'!='", "'<'", "'>'", "'<='", "'>='", "'.'", "';'", "','", "'('", "')'", 
		"'{'", "'}'", "'['", "']'"
	};
	
	private static readonly string[] _SymbolicNames = {
		null, "LIST", "INT_ID", "STRING_ID", "CHAR_ID", "BOOL_ID", "DOUBLE_ID", 
		"CLASS", "USING", "VOID", "IF", "ELSE", "WHILE", "FOR", "BREAK", "RETURN", 
		"READ", "WRITE", "NEW", "DELMETHOD", "ADDMETHOD", "LENMETHOD", "DEL", 
		"ADD", "LEN", "BOOL", "INT", "DOUBLE", "STRINGCONST", "CHARCONST", "EscapeSequence", 
		"ASSIGN", "AND", "OR", "PLUS", "MINUS", "PLUSPLUS", "MINUSMINUS", "MULT", 
		"DIV", "MOD", "EQUALS", "NOTEQUALS", "LESSTHAN", "GREATERTHAN", "LESSOREQUALS", 
		"GREATOREQUALS", "DOT", "SEMICOLON", "COMMA", "LEFTPAREN", "RIGHTPAREN", 
		"LEFTBRACK", "RIGHTBRACK", "LEFTSBRACK", "RIGHTSBRACK", "IDENTIFIER", 
		"COMMENT", "BLOCKCOMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MiniCSharpParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MiniCSharpParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MiniCSharpParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MiniCSharpParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(MiniCSharpParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTBRACK() { return GetToken(MiniCSharpParser.LEFTBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTBRACK() { return GetToken(MiniCSharpParser.RIGHTBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MiniCSharpParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UsingContext[] @using() {
			return GetRuleContexts<UsingContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public UsingContext @using(int i) {
			return GetRuleContext<UsingContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassDeclContext[] classDecl() {
			return GetRuleContexts<ClassDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassDeclContext classDecl(int i) {
			return GetRuleContext<ClassDeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MethodDeclContext[] methodDecl() {
			return GetRuleContexts<MethodDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MethodDeclContext methodDecl(int i) {
			return GetRuleContext<MethodDeclContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==USING) {
				{
				{
				State = 44;
				@using();
				}
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 50;
			Match(CLASS);
			State = 51;
			ident();
			State = 52;
			Match(LEFTBRACK);
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 72057594037928702L) != 0) {
				{
				State = 56;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
				case 1:
					{
					State = 53;
					varDecl();
					}
					break;
				case 2:
					{
					State = 54;
					classDecl();
					}
					break;
				case 3:
					{
					State = 55;
					methodDecl();
					}
					break;
				}
				}
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 61;
			Match(RIGHTBRACK);
			State = 62;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UsingContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USING() { return GetToken(MiniCSharpParser.USING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MiniCSharpParser.SEMICOLON, 0); }
		public UsingContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_using; } }
	}

	[RuleVersion(0)]
	public UsingContext @using() {
		UsingContext _localctx = new UsingContext(Context, State);
		EnterRule(_localctx, 2, RULE_using);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			Match(USING);
			State = 65;
			ident();
			State = 66;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarDeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext[] ident() {
			return GetRuleContexts<IdentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident(int i) {
			return GetRuleContext<IdentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MiniCSharpParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MiniCSharpParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MiniCSharpParser.COMMA, i);
		}
		public VarDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_varDecl; } }
	}

	[RuleVersion(0)]
	public VarDeclContext varDecl() {
		VarDeclContext _localctx = new VarDeclContext(Context, State);
		EnterRule(_localctx, 4, RULE_varDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			type();
			State = 69;
			ident();
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 70;
				Match(COMMA);
				State = 71;
				ident();
				}
				}
				State = 76;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 77;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassDeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(MiniCSharpParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTBRACK() { return GetToken(MiniCSharpParser.LEFTBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTBRACK() { return GetToken(MiniCSharpParser.RIGHTBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		public ClassDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classDecl; } }
	}

	[RuleVersion(0)]
	public ClassDeclContext classDecl() {
		ClassDeclContext _localctx = new ClassDeclContext(Context, State);
		EnterRule(_localctx, 6, RULE_classDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			Match(CLASS);
			State = 80;
			ident();
			State = 81;
			Match(LEFTBRACK);
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 72057594037928062L) != 0) {
				{
				{
				State = 82;
				varDecl();
				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 88;
			Match(RIGHTBRACK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodDeclContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTPAREN() { return GetToken(MiniCSharpParser.LEFTPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTPAREN() { return GetToken(MiniCSharpParser.RIGHTPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VOID() { return GetToken(MiniCSharpParser.VOID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FormParsContext formPars() {
			return GetRuleContext<FormParsContext>(0);
		}
		public MethodDeclContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodDecl; } }
	}

	[RuleVersion(0)]
	public MethodDeclContext methodDecl() {
		MethodDeclContext _localctx = new MethodDeclContext(Context, State);
		EnterRule(_localctx, 8, RULE_methodDecl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LIST:
			case INT_ID:
			case STRING_ID:
			case CHAR_ID:
			case BOOL_ID:
			case DOUBLE_ID:
			case IDENTIFIER:
				{
				State = 90;
				type();
				}
				break;
			case VOID:
				{
				State = 91;
				Match(VOID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 94;
			ident();
			State = 95;
			Match(LEFTPAREN);
			State = 97;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (((_la) & ~0x3f) == 0 && ((1L << _la) & 72057594037928062L) != 0) {
				{
				State = 96;
				formPars();
				}
			}

			State = 99;
			Match(RIGHTPAREN);
			State = 100;
			block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormParsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext[] ident() {
			return GetRuleContexts<IdentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident(int i) {
			return GetRuleContext<IdentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MiniCSharpParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MiniCSharpParser.COMMA, i);
		}
		public FormParsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formPars; } }
	}

	[RuleVersion(0)]
	public FormParsContext formPars() {
		FormParsContext _localctx = new FormParsContext(Context, State);
		EnterRule(_localctx, 10, RULE_formPars);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			type();
			State = 103;
			ident();
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 104;
				Match(COMMA);
				State = 105;
				type();
				State = 106;
				ident();
				}
				}
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTSBRACK() { return GetToken(MiniCSharpParser.LEFTSBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTSBRACK() { return GetToken(MiniCSharpParser.RIGHTSBRACK, 0); }
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 12, RULE_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			ident();
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==LEFTSBRACK) {
				{
				State = 114;
				Match(LEFTSBRACK);
				State = 115;
				Match(RIGHTSBRACK);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DesignatorContext[] designator() {
			return GetRuleContexts<DesignatorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DesignatorContext designator(int i) {
			return GetRuleContext<DesignatorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMICOLON() { return GetTokens(MiniCSharpParser.SEMICOLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON(int i) {
			return GetToken(MiniCSharpParser.SEMICOLON, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MiniCSharpParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTPAREN() { return GetToken(MiniCSharpParser.LEFTPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTPAREN() { return GetToken(MiniCSharpParser.RIGHTPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUSPLUS() { return GetToken(MiniCSharpParser.PLUSPLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUSMINUS() { return GetToken(MiniCSharpParser.MINUSMINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ActParsContext actPars() {
			return GetRuleContext<ActParsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(MiniCSharpParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(MiniCSharpParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FOR() { return GetToken(MiniCSharpParser.FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(MiniCSharpParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BREAK() { return GetToken(MiniCSharpParser.BREAK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(MiniCSharpParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode READ() { return GetToken(MiniCSharpParser.READ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WRITE() { return GetToken(MiniCSharpParser.WRITE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MiniCSharpParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MiniCSharpParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(MiniCSharpParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(MiniCSharpParser.INT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(MiniCSharpParser.DOUBLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADDMETHOD() { return GetToken(MiniCSharpParser.ADDMETHOD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LENMETHOD() { return GetToken(MiniCSharpParser.LENMETHOD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DELMETHOD() { return GetToken(MiniCSharpParser.DELMETHOD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_statement);
		int _la;
		try {
			State = 219;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 118;
				designator();
				State = 128;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case ASSIGN:
					{
					State = 119;
					Match(ASSIGN);
					State = 120;
					expr();
					}
					break;
				case LEFTPAREN:
					{
					State = 121;
					Match(LEFTPAREN);
					State = 123;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (((_la) & ~0x3f) == 0 && ((1L << _la) & 73183529344958590L) != 0) {
						{
						State = 122;
						actPars();
						}
					}

					State = 125;
					Match(RIGHTPAREN);
					}
					break;
				case PLUSPLUS:
					{
					State = 126;
					Match(PLUSPLUS);
					}
					break;
				case MINUSMINUS:
					{
					State = 127;
					Match(MINUSMINUS);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 130;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 132;
				Match(IF);
				State = 133;
				Match(LEFTPAREN);
				State = 134;
				condition();
				State = 135;
				Match(RIGHTPAREN);
				State = 136;
				statement();
				State = 139;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
				case 1:
					{
					State = 137;
					Match(ELSE);
					State = 138;
					statement();
					}
					break;
				}
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 141;
				Match(FOR);
				State = 142;
				Match(LEFTPAREN);
				State = 143;
				expr();
				State = 144;
				Match(SEMICOLON);
				State = 146;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (((_la) & ~0x3f) == 0 && ((1L << _la) & 73183529344958590L) != 0) {
					{
					State = 145;
					condition();
					}
				}

				State = 148;
				Match(SEMICOLON);
				State = 150;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (((_la) & ~0x3f) == 0 && ((1L << _la) & 76842668642268286L) != 0) {
					{
					State = 149;
					statement();
					}
				}

				State = 152;
				Match(RIGHTPAREN);
				State = 153;
				statement();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 155;
				Match(WHILE);
				State = 156;
				Match(LEFTPAREN);
				State = 157;
				condition();
				State = 158;
				Match(RIGHTPAREN);
				State = 159;
				statement();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 161;
				Match(BREAK);
				State = 162;
				Match(SEMICOLON);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 163;
				Match(RETURN);
				State = 165;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (((_la) & ~0x3f) == 0 && ((1L << _la) & 73183529344958590L) != 0) {
					{
					State = 164;
					expr();
					}
				}

				State = 167;
				Match(SEMICOLON);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 168;
				Match(READ);
				State = 169;
				Match(LEFTPAREN);
				State = 170;
				designator();
				State = 171;
				Match(RIGHTPAREN);
				State = 172;
				Match(SEMICOLON);
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 174;
				Match(WRITE);
				State = 175;
				Match(LEFTPAREN);
				State = 176;
				expr();
				State = 179;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==COMMA) {
					{
					State = 177;
					Match(COMMA);
					State = 178;
					_la = TokenStream.LA(1);
					if ( !(_la==INT || _la==DOUBLE) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 181;
				Match(RIGHTPAREN);
				State = 182;
				Match(SEMICOLON);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 184;
				designator();
				State = 185;
				Match(ADDMETHOD);
				State = 186;
				Match(LEFTPAREN);
				State = 189;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case LIST:
				case INT_ID:
				case STRING_ID:
				case CHAR_ID:
				case BOOL_ID:
				case DOUBLE_ID:
				case IDENTIFIER:
					{
					State = 187;
					designator();
					}
					break;
				case INT:
					{
					State = 188;
					Match(INT);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 198;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 191;
					Match(COMMA);
					State = 194;
					ErrorHandler.Sync(this);
					switch (TokenStream.LA(1)) {
					case LIST:
					case INT_ID:
					case STRING_ID:
					case CHAR_ID:
					case BOOL_ID:
					case DOUBLE_ID:
					case IDENTIFIER:
						{
						State = 192;
						designator();
						}
						break;
					case INT:
						{
						State = 193;
						Match(INT);
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					}
					}
					State = 200;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 201;
				Match(RIGHTPAREN);
				State = 202;
				Match(SEMICOLON);
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 204;
				designator();
				State = 205;
				Match(LENMETHOD);
				State = 206;
				Match(LEFTPAREN);
				State = 207;
				Match(RIGHTPAREN);
				State = 208;
				Match(SEMICOLON);
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 210;
				designator();
				State = 211;
				Match(DELMETHOD);
				State = 212;
				Match(LEFTPAREN);
				State = 213;
				Match(INT);
				State = 214;
				Match(RIGHTPAREN);
				State = 215;
				Match(SEMICOLON);
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 217;
				block();
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 218;
				Match(SEMICOLON);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTBRACK() { return GetToken(MiniCSharpParser.LEFTBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTBRACK() { return GetToken(MiniCSharpParser.RIGHTBRACK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclContext[] varDecl() {
			return GetRuleContexts<VarDeclContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public VarDeclContext varDecl(int i) {
			return GetRuleContext<VarDeclContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 16, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 221;
			Match(LEFTBRACK);
			State = 226;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 76842668642268286L) != 0) {
				{
				State = 224;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
				case 1:
					{
					State = 222;
					varDecl();
					}
					break;
				case 2:
					{
					State = 223;
					statement();
					}
					break;
				}
				}
				State = 228;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 229;
			Match(RIGHTBRACK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActParsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MiniCSharpParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MiniCSharpParser.COMMA, i);
		}
		public ActParsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actPars; } }
	}

	[RuleVersion(0)]
	public ActParsContext actPars() {
		ActParsContext _localctx = new ActParsContext(Context, State);
		EnterRule(_localctx, 18, RULE_actPars);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 231;
			expr();
			State = 236;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 232;
				Match(COMMA);
				State = 233;
				expr();
				}
				}
				State = 238;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CondTermContext[] condTerm() {
			return GetRuleContexts<CondTermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CondTermContext condTerm(int i) {
			return GetRuleContext<CondTermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OR() { return GetTokens(MiniCSharpParser.OR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR(int i) {
			return GetToken(MiniCSharpParser.OR, i);
		}
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 20, RULE_condition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 239;
			condTerm();
			State = 244;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OR) {
				{
				{
				State = 240;
				Match(OR);
				State = 241;
				condTerm();
				}
				}
				State = 246;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondTermContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CondFactContext[] condFact() {
			return GetRuleContexts<CondFactContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public CondFactContext condFact(int i) {
			return GetRuleContext<CondFactContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AND() { return GetTokens(MiniCSharpParser.AND); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND(int i) {
			return GetToken(MiniCSharpParser.AND, i);
		}
		public CondTermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condTerm; } }
	}

	[RuleVersion(0)]
	public CondTermContext condTerm() {
		CondTermContext _localctx = new CondTermContext(Context, State);
		EnterRule(_localctx, 22, RULE_condTerm);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 247;
			condFact();
			State = 252;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==AND) {
				{
				{
				State = 248;
				Match(AND);
				State = 249;
				condFact();
				}
				}
				State = 254;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondFactContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelopContext relop() {
			return GetRuleContext<RelopContext>(0);
		}
		public CondFactContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condFact; } }
	}

	[RuleVersion(0)]
	public CondFactContext condFact() {
		CondFactContext _localctx = new CondFactContext(Context, State);
		EnterRule(_localctx, 24, RULE_condFact);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 255;
			expr();
			State = 256;
			relop();
			State = 257;
			expr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CastContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTPAREN() { return GetToken(MiniCSharpParser.LEFTPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTPAREN() { return GetToken(MiniCSharpParser.RIGHTPAREN, 0); }
		public CastContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cast; } }
	}

	[RuleVersion(0)]
	public CastContext cast() {
		CastContext _localctx = new CastContext(Context, State);
		EnterRule(_localctx, 26, RULE_cast);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 259;
			Match(LEFTPAREN);
			State = 260;
			type();
			State = 261;
			Match(RIGHTPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(MiniCSharpParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CastContext cast() {
			return GetRuleContext<CastContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddopContext[] addop() {
			return GetRuleContexts<AddopContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddopContext addop(int i) {
			return GetRuleContext<AddopContext>(i);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 28, RULE_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 264;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MINUS) {
				{
				State = 263;
				Match(MINUS);
				}
			}

			State = 267;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
			case 1:
				{
				State = 266;
				cast();
				}
				break;
			}
			State = 269;
			term();
			State = 275;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PLUS || _la==MINUS) {
				{
				{
				State = 270;
				addop();
				State = 271;
				term();
				}
				}
				State = 277;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext[] factor() {
			return GetRuleContexts<FactorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor(int i) {
			return GetRuleContext<FactorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulopContext[] mulop() {
			return GetRuleContexts<MulopContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulopContext mulop(int i) {
			return GetRuleContext<MulopContext>(i);
		}
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 30, RULE_term);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 278;
			factor();
			State = 284;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (((_la) & ~0x3f) == 0 && ((1L << _la) & 1924145348608L) != 0) {
				{
				{
				State = 279;
				mulop();
				State = 280;
				factor();
				}
				}
				State = 286;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FactorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DesignatorContext designator() {
			return GetRuleContext<DesignatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTPAREN() { return GetToken(MiniCSharpParser.LEFTPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTPAREN() { return GetToken(MiniCSharpParser.RIGHTPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ActParsContext actPars() {
			return GetRuleContext<ActParsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARCONST() { return GetToken(MiniCSharpParser.CHARCONST, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRINGCONST() { return GetToken(MiniCSharpParser.STRINGCONST, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(MiniCSharpParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(MiniCSharpParser.DOUBLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL() { return GetToken(MiniCSharpParser.BOOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(MiniCSharpParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident() {
			return GetRuleContext<IdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public FactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factor; } }
	}

	[RuleVersion(0)]
	public FactorContext factor() {
		FactorContext _localctx = new FactorContext(Context, State);
		EnterRule(_localctx, 32, RULE_factor);
		int _la;
		try {
			State = 306;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case LIST:
			case INT_ID:
			case STRING_ID:
			case CHAR_ID:
			case BOOL_ID:
			case DOUBLE_ID:
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 287;
				designator();
				State = 293;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==LEFTPAREN) {
					{
					State = 288;
					Match(LEFTPAREN);
					State = 290;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (((_la) & ~0x3f) == 0 && ((1L << _la) & 73183529344958590L) != 0) {
						{
						State = 289;
						actPars();
						}
					}

					State = 292;
					Match(RIGHTPAREN);
					}
				}

				}
				break;
			case CHARCONST:
				EnterOuterAlt(_localctx, 2);
				{
				State = 295;
				Match(CHARCONST);
				}
				break;
			case STRINGCONST:
				EnterOuterAlt(_localctx, 3);
				{
				State = 296;
				Match(STRINGCONST);
				}
				break;
			case INT:
				EnterOuterAlt(_localctx, 4);
				{
				State = 297;
				Match(INT);
				}
				break;
			case DOUBLE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 298;
				Match(DOUBLE);
				}
				break;
			case BOOL:
				EnterOuterAlt(_localctx, 6);
				{
				State = 299;
				Match(BOOL);
				}
				break;
			case NEW:
				EnterOuterAlt(_localctx, 7);
				{
				State = 300;
				Match(NEW);
				State = 301;
				ident();
				}
				break;
			case LEFTPAREN:
				EnterOuterAlt(_localctx, 8);
				{
				State = 302;
				Match(LEFTPAREN);
				State = 303;
				expr();
				State = 304;
				Match(RIGHTPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DesignatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext[] ident() {
			return GetRuleContexts<IdentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentContext ident(int i) {
			return GetRuleContext<IdentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOT() { return GetTokens(MiniCSharpParser.DOT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT(int i) {
			return GetToken(MiniCSharpParser.DOT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LEFTSBRACK() { return GetTokens(MiniCSharpParser.LEFTSBRACK); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LEFTSBRACK(int i) {
			return GetToken(MiniCSharpParser.LEFTSBRACK, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RIGHTSBRACK() { return GetTokens(MiniCSharpParser.RIGHTSBRACK); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RIGHTSBRACK(int i) {
			return GetToken(MiniCSharpParser.RIGHTSBRACK, i);
		}
		public DesignatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_designator; } }
	}

	[RuleVersion(0)]
	public DesignatorContext designator() {
		DesignatorContext _localctx = new DesignatorContext(Context, State);
		EnterRule(_localctx, 34, RULE_designator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 308;
			ident();
			State = 317;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT || _la==LEFTSBRACK) {
				{
				State = 315;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case DOT:
					{
					State = 309;
					Match(DOT);
					State = 310;
					ident();
					}
					break;
				case LEFTSBRACK:
					{
					State = 311;
					Match(LEFTSBRACK);
					State = 312;
					expr();
					State = 313;
					Match(RIGHTSBRACK);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 319;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelopContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(MiniCSharpParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQUALS() { return GetToken(MiniCSharpParser.NOTEQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATERTHAN() { return GetToken(MiniCSharpParser.GREATERTHAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATOREQUALS() { return GetToken(MiniCSharpParser.GREATOREQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESSTHAN() { return GetToken(MiniCSharpParser.LESSTHAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESSOREQUALS() { return GetToken(MiniCSharpParser.LESSOREQUALS, 0); }
		public RelopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relop; } }
	}

	[RuleVersion(0)]
	public RelopContext relop() {
		RelopContext _localctx = new RelopContext(Context, State);
		EnterRule(_localctx, 36, RULE_relop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 320;
			_la = TokenStream.LA(1);
			if ( !(((_la) & ~0x3f) == 0 && ((1L << _la) & 138538465099776L) != 0) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddopContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(MiniCSharpParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(MiniCSharpParser.MINUS, 0); }
		public AddopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addop; } }
	}

	[RuleVersion(0)]
	public AddopContext addop() {
		AddopContext _localctx = new AddopContext(Context, State);
		EnterRule(_localctx, 38, RULE_addop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 322;
			_la = TokenStream.LA(1);
			if ( !(_la==PLUS || _la==MINUS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulopContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(MiniCSharpParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV() { return GetToken(MiniCSharpParser.DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MOD() { return GetToken(MiniCSharpParser.MOD, 0); }
		public MulopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mulop; } }
	}

	[RuleVersion(0)]
	public MulopContext mulop() {
		MulopContext _localctx = new MulopContext(Context, State);
		EnterRule(_localctx, 40, RULE_mulop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 324;
			_la = TokenStream.LA(1);
			if ( !(((_la) & ~0x3f) == 0 && ((1L << _la) & 1924145348608L) != 0) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_ID() { return GetToken(MiniCSharpParser.INT_ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR_ID() { return GetToken(MiniCSharpParser.CHAR_ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_ID() { return GetToken(MiniCSharpParser.DOUBLE_ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL_ID() { return GetToken(MiniCSharpParser.BOOL_ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_ID() { return GetToken(MiniCSharpParser.STRING_ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MiniCSharpParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LIST() { return GetToken(MiniCSharpParser.LIST, 0); }
		public IdentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ident; } }
	}

	[RuleVersion(0)]
	public IdentContext ident() {
		IdentContext _localctx = new IdentContext(Context, State);
		EnterRule(_localctx, 42, RULE_ident);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 326;
			_la = TokenStream.LA(1);
			if ( !(((_la) & ~0x3f) == 0 && ((1L << _la) & 72057594037928062L) != 0) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,59,329,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		1,0,5,0,46,8,0,10,0,12,0,49,9,0,1,0,1,0,1,0,1,0,1,0,1,0,5,0,57,8,0,10,
		0,12,0,60,9,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,2,5,2,73,8,2,10,
		2,12,2,76,9,2,1,2,1,2,1,3,1,3,1,3,1,3,5,3,84,8,3,10,3,12,3,87,9,3,1,3,
		1,3,1,4,1,4,3,4,93,8,4,1,4,1,4,1,4,3,4,98,8,4,1,4,1,4,1,4,1,5,1,5,1,5,
		1,5,1,5,1,5,5,5,109,8,5,10,5,12,5,112,9,5,1,6,1,6,1,6,3,6,117,8,6,1,7,
		1,7,1,7,1,7,1,7,3,7,124,8,7,1,7,1,7,1,7,3,7,129,8,7,1,7,1,7,1,7,1,7,1,
		7,1,7,1,7,1,7,1,7,3,7,140,8,7,1,7,1,7,1,7,1,7,1,7,3,7,147,8,7,1,7,1,7,
		3,7,151,8,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,3,7,166,
		8,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,3,7,180,8,7,1,7,1,
		7,1,7,1,7,1,7,1,7,1,7,1,7,3,7,190,8,7,1,7,1,7,1,7,3,7,195,8,7,5,7,197,
		8,7,10,7,12,7,200,9,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,
		1,7,1,7,1,7,1,7,1,7,1,7,3,7,220,8,7,1,8,1,8,1,8,5,8,225,8,8,10,8,12,8,
		228,9,8,1,8,1,8,1,9,1,9,1,9,5,9,235,8,9,10,9,12,9,238,9,9,1,10,1,10,1,
		10,5,10,243,8,10,10,10,12,10,246,9,10,1,11,1,11,1,11,5,11,251,8,11,10,
		11,12,11,254,9,11,1,12,1,12,1,12,1,12,1,13,1,13,1,13,1,13,1,14,3,14,265,
		8,14,1,14,3,14,268,8,14,1,14,1,14,1,14,1,14,5,14,274,8,14,10,14,12,14,
		277,9,14,1,15,1,15,1,15,1,15,5,15,283,8,15,10,15,12,15,286,9,15,1,16,1,
		16,1,16,3,16,291,8,16,1,16,3,16,294,8,16,1,16,1,16,1,16,1,16,1,16,1,16,
		1,16,1,16,1,16,1,16,1,16,3,16,307,8,16,1,17,1,17,1,17,1,17,1,17,1,17,1,
		17,5,17,316,8,17,10,17,12,17,319,9,17,1,18,1,18,1,19,1,19,1,20,1,20,1,
		21,1,21,1,21,0,0,22,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,
		38,40,42,0,5,1,0,26,27,1,0,41,46,1,0,34,35,1,0,38,40,2,0,1,6,56,56,360,
		0,47,1,0,0,0,2,64,1,0,0,0,4,68,1,0,0,0,6,79,1,0,0,0,8,92,1,0,0,0,10,102,
		1,0,0,0,12,113,1,0,0,0,14,219,1,0,0,0,16,221,1,0,0,0,18,231,1,0,0,0,20,
		239,1,0,0,0,22,247,1,0,0,0,24,255,1,0,0,0,26,259,1,0,0,0,28,264,1,0,0,
		0,30,278,1,0,0,0,32,306,1,0,0,0,34,308,1,0,0,0,36,320,1,0,0,0,38,322,1,
		0,0,0,40,324,1,0,0,0,42,326,1,0,0,0,44,46,3,2,1,0,45,44,1,0,0,0,46,49,
		1,0,0,0,47,45,1,0,0,0,47,48,1,0,0,0,48,50,1,0,0,0,49,47,1,0,0,0,50,51,
		5,7,0,0,51,52,3,42,21,0,52,58,5,52,0,0,53,57,3,4,2,0,54,57,3,6,3,0,55,
		57,3,8,4,0,56,53,1,0,0,0,56,54,1,0,0,0,56,55,1,0,0,0,57,60,1,0,0,0,58,
		56,1,0,0,0,58,59,1,0,0,0,59,61,1,0,0,0,60,58,1,0,0,0,61,62,5,53,0,0,62,
		63,5,0,0,1,63,1,1,0,0,0,64,65,5,8,0,0,65,66,3,42,21,0,66,67,5,48,0,0,67,
		3,1,0,0,0,68,69,3,12,6,0,69,74,3,42,21,0,70,71,5,49,0,0,71,73,3,42,21,
		0,72,70,1,0,0,0,73,76,1,0,0,0,74,72,1,0,0,0,74,75,1,0,0,0,75,77,1,0,0,
		0,76,74,1,0,0,0,77,78,5,48,0,0,78,5,1,0,0,0,79,80,5,7,0,0,80,81,3,42,21,
		0,81,85,5,52,0,0,82,84,3,4,2,0,83,82,1,0,0,0,84,87,1,0,0,0,85,83,1,0,0,
		0,85,86,1,0,0,0,86,88,1,0,0,0,87,85,1,0,0,0,88,89,5,53,0,0,89,7,1,0,0,
		0,90,93,3,12,6,0,91,93,5,9,0,0,92,90,1,0,0,0,92,91,1,0,0,0,93,94,1,0,0,
		0,94,95,3,42,21,0,95,97,5,50,0,0,96,98,3,10,5,0,97,96,1,0,0,0,97,98,1,
		0,0,0,98,99,1,0,0,0,99,100,5,51,0,0,100,101,3,16,8,0,101,9,1,0,0,0,102,
		103,3,12,6,0,103,110,3,42,21,0,104,105,5,49,0,0,105,106,3,12,6,0,106,107,
		3,42,21,0,107,109,1,0,0,0,108,104,1,0,0,0,109,112,1,0,0,0,110,108,1,0,
		0,0,110,111,1,0,0,0,111,11,1,0,0,0,112,110,1,0,0,0,113,116,3,42,21,0,114,
		115,5,54,0,0,115,117,5,55,0,0,116,114,1,0,0,0,116,117,1,0,0,0,117,13,1,
		0,0,0,118,128,3,34,17,0,119,120,5,31,0,0,120,129,3,28,14,0,121,123,5,50,
		0,0,122,124,3,18,9,0,123,122,1,0,0,0,123,124,1,0,0,0,124,125,1,0,0,0,125,
		129,5,51,0,0,126,129,5,36,0,0,127,129,5,37,0,0,128,119,1,0,0,0,128,121,
		1,0,0,0,128,126,1,0,0,0,128,127,1,0,0,0,129,130,1,0,0,0,130,131,5,48,0,
		0,131,220,1,0,0,0,132,133,5,10,0,0,133,134,5,50,0,0,134,135,3,20,10,0,
		135,136,5,51,0,0,136,139,3,14,7,0,137,138,5,11,0,0,138,140,3,14,7,0,139,
		137,1,0,0,0,139,140,1,0,0,0,140,220,1,0,0,0,141,142,5,13,0,0,142,143,5,
		50,0,0,143,144,3,28,14,0,144,146,5,48,0,0,145,147,3,20,10,0,146,145,1,
		0,0,0,146,147,1,0,0,0,147,148,1,0,0,0,148,150,5,48,0,0,149,151,3,14,7,
		0,150,149,1,0,0,0,150,151,1,0,0,0,151,152,1,0,0,0,152,153,5,51,0,0,153,
		154,3,14,7,0,154,220,1,0,0,0,155,156,5,12,0,0,156,157,5,50,0,0,157,158,
		3,20,10,0,158,159,5,51,0,0,159,160,3,14,7,0,160,220,1,0,0,0,161,162,5,
		14,0,0,162,220,5,48,0,0,163,165,5,15,0,0,164,166,3,28,14,0,165,164,1,0,
		0,0,165,166,1,0,0,0,166,167,1,0,0,0,167,220,5,48,0,0,168,169,5,16,0,0,
		169,170,5,50,0,0,170,171,3,34,17,0,171,172,5,51,0,0,172,173,5,48,0,0,173,
		220,1,0,0,0,174,175,5,17,0,0,175,176,5,50,0,0,176,179,3,28,14,0,177,178,
		5,49,0,0,178,180,7,0,0,0,179,177,1,0,0,0,179,180,1,0,0,0,180,181,1,0,0,
		0,181,182,5,51,0,0,182,183,5,48,0,0,183,220,1,0,0,0,184,185,3,34,17,0,
		185,186,5,20,0,0,186,189,5,50,0,0,187,190,3,34,17,0,188,190,5,26,0,0,189,
		187,1,0,0,0,189,188,1,0,0,0,190,198,1,0,0,0,191,194,5,49,0,0,192,195,3,
		34,17,0,193,195,5,26,0,0,194,192,1,0,0,0,194,193,1,0,0,0,195,197,1,0,0,
		0,196,191,1,0,0,0,197,200,1,0,0,0,198,196,1,0,0,0,198,199,1,0,0,0,199,
		201,1,0,0,0,200,198,1,0,0,0,201,202,5,51,0,0,202,203,5,48,0,0,203,220,
		1,0,0,0,204,205,3,34,17,0,205,206,5,21,0,0,206,207,5,50,0,0,207,208,5,
		51,0,0,208,209,5,48,0,0,209,220,1,0,0,0,210,211,3,34,17,0,211,212,5,19,
		0,0,212,213,5,50,0,0,213,214,5,26,0,0,214,215,5,51,0,0,215,216,5,48,0,
		0,216,220,1,0,0,0,217,220,3,16,8,0,218,220,5,48,0,0,219,118,1,0,0,0,219,
		132,1,0,0,0,219,141,1,0,0,0,219,155,1,0,0,0,219,161,1,0,0,0,219,163,1,
		0,0,0,219,168,1,0,0,0,219,174,1,0,0,0,219,184,1,0,0,0,219,204,1,0,0,0,
		219,210,1,0,0,0,219,217,1,0,0,0,219,218,1,0,0,0,220,15,1,0,0,0,221,226,
		5,52,0,0,222,225,3,4,2,0,223,225,3,14,7,0,224,222,1,0,0,0,224,223,1,0,
		0,0,225,228,1,0,0,0,226,224,1,0,0,0,226,227,1,0,0,0,227,229,1,0,0,0,228,
		226,1,0,0,0,229,230,5,53,0,0,230,17,1,0,0,0,231,236,3,28,14,0,232,233,
		5,49,0,0,233,235,3,28,14,0,234,232,1,0,0,0,235,238,1,0,0,0,236,234,1,0,
		0,0,236,237,1,0,0,0,237,19,1,0,0,0,238,236,1,0,0,0,239,244,3,22,11,0,240,
		241,5,33,0,0,241,243,3,22,11,0,242,240,1,0,0,0,243,246,1,0,0,0,244,242,
		1,0,0,0,244,245,1,0,0,0,245,21,1,0,0,0,246,244,1,0,0,0,247,252,3,24,12,
		0,248,249,5,32,0,0,249,251,3,24,12,0,250,248,1,0,0,0,251,254,1,0,0,0,252,
		250,1,0,0,0,252,253,1,0,0,0,253,23,1,0,0,0,254,252,1,0,0,0,255,256,3,28,
		14,0,256,257,3,36,18,0,257,258,3,28,14,0,258,25,1,0,0,0,259,260,5,50,0,
		0,260,261,3,12,6,0,261,262,5,51,0,0,262,27,1,0,0,0,263,265,5,35,0,0,264,
		263,1,0,0,0,264,265,1,0,0,0,265,267,1,0,0,0,266,268,3,26,13,0,267,266,
		1,0,0,0,267,268,1,0,0,0,268,269,1,0,0,0,269,275,3,30,15,0,270,271,3,38,
		19,0,271,272,3,30,15,0,272,274,1,0,0,0,273,270,1,0,0,0,274,277,1,0,0,0,
		275,273,1,0,0,0,275,276,1,0,0,0,276,29,1,0,0,0,277,275,1,0,0,0,278,284,
		3,32,16,0,279,280,3,40,20,0,280,281,3,32,16,0,281,283,1,0,0,0,282,279,
		1,0,0,0,283,286,1,0,0,0,284,282,1,0,0,0,284,285,1,0,0,0,285,31,1,0,0,0,
		286,284,1,0,0,0,287,293,3,34,17,0,288,290,5,50,0,0,289,291,3,18,9,0,290,
		289,1,0,0,0,290,291,1,0,0,0,291,292,1,0,0,0,292,294,5,51,0,0,293,288,1,
		0,0,0,293,294,1,0,0,0,294,307,1,0,0,0,295,307,5,29,0,0,296,307,5,28,0,
		0,297,307,5,26,0,0,298,307,5,27,0,0,299,307,5,25,0,0,300,301,5,18,0,0,
		301,307,3,42,21,0,302,303,5,50,0,0,303,304,3,28,14,0,304,305,5,51,0,0,
		305,307,1,0,0,0,306,287,1,0,0,0,306,295,1,0,0,0,306,296,1,0,0,0,306,297,
		1,0,0,0,306,298,1,0,0,0,306,299,1,0,0,0,306,300,1,0,0,0,306,302,1,0,0,
		0,307,33,1,0,0,0,308,317,3,42,21,0,309,310,5,47,0,0,310,316,3,42,21,0,
		311,312,5,54,0,0,312,313,3,28,14,0,313,314,5,55,0,0,314,316,1,0,0,0,315,
		309,1,0,0,0,315,311,1,0,0,0,316,319,1,0,0,0,317,315,1,0,0,0,317,318,1,
		0,0,0,318,35,1,0,0,0,319,317,1,0,0,0,320,321,7,1,0,0,321,37,1,0,0,0,322,
		323,7,2,0,0,323,39,1,0,0,0,324,325,7,3,0,0,325,41,1,0,0,0,326,327,7,4,
		0,0,327,43,1,0,0,0,34,47,56,58,74,85,92,97,110,116,123,128,139,146,150,
		165,179,189,194,198,219,224,226,236,244,252,264,267,275,284,290,293,306,
		315,317
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
